version: 0.2

env:
    exported-variables:
        - BuildID
        - BuildTag

phases:
    install:
        commands:
            - "curl -s $TF_ZIP_URL -o terraform.zip"
            - "unzip terraform.zip -d /usr/local/bin"
            - "chmod 755 /usr/local/bin/terraform"
    pre_build:
        commands:
            - "terraform init --backend-config=\"bucket=$BUCKET\" --backend-config=\"key=$STAGE.tfstate\" --backend-config=\"region=$REGION\""
    build:
        commands:
            - "terraform plan -var=\"stage=$STAGE\" -var=\"region=$REGION\" -out=$STAGE-terraform.tfplan"
            - "export BuildID=`echo $CODEBUILD_BUILD_ID | cut -d: -f1`"
            - "export BuildTag=`echo $CODEBUILD_BUILD_ID | cut -d: -f2`"

artifacts:
    name: TerraformPlan
    files:
        - $STAGE-terraform.tfplan
